CON=ODBC(1)
*SQLEXEC(CON,"SELECT B.NAME,A.beforename,SEARCHNAME FROM HEADINFODETAIL A INNER JOIN [quanguoguishang] B ON A.NAME=B.SEARCHNAME WHERE HANGYE IS NULL","TMP")
SELECT TMP
GO TOP
DO WHIL .NOT. EOF()
	X1=NAME
	X2=beforename
	X3=SEARCHNAME 
	SQLEXEC(CON,"SELECT TOP 1 [ап 17] XX FROM [census2008quanguo] WHERE [name]=?X1  OR NAME=?X3") && OR ?X2 LIKE '%NAME%'
	IF RECCOUNT()=1
		Y=XX
		SQLEXEC(CON,"UPDATE HEADINFODETAIL SET HANGYE=?Y WHERE NAME=?X3 ")
	ENDIF
	SELECT TMP
	WAIT WINDOW TRANSFORM(RECNO()) NOWAIT 
	SKIP
ENDDO	